name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.0'

    steps:
    - uses: actions/checkout@v3
    - name: 'install deps'
      run: "sudo apt install -y libfreetype6-dev gsfonts libmagickwand-dev imagemagick"
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      env:
        UNSPLASH_API_KEY:  ${{ secrets.UNSPLASH_API_KEY }}
      run: bundle exec rake
